/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DaftarRouteImport } from './routes/daftar'
import { Route as DihantarRouteImport } from './routes/dihantar'
import { Route as DrafRouteImport } from './routes/draf'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PetiMasukRouteImport } from './routes/peti-masuk'
import { Route as KTokenRouteImport } from './routes/k/$token'
import { Route as LihatIdRouteImport } from './routes/lihat/$id'
import { Route as StudioIndexRouteImport } from './routes/studio/index'
import { Route as StudioIdRouteImport } from './routes/studio/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DaftarRoute = DaftarRouteImport.update({
  id: '/daftar',
  path: '/daftar',
  getParentRoute: () => rootRouteImport,
} as any)
const DihantarRoute = DihantarRouteImport.update({
  id: '/dihantar',
  path: '/dihantar',
  getParentRoute: () => rootRouteImport,
} as any)
const DrafRoute = DrafRouteImport.update({
  id: '/draf',
  path: '/draf',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PetiMasukRoute = PetiMasukRouteImport.update({
  id: '/peti-masuk',
  path: '/peti-masuk',
  getParentRoute: () => rootRouteImport,
} as any)
const KTokenRoute = KTokenRouteImport.update({
  id: '/k/$token',
  path: '/k/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const LihatIdRoute = LihatIdRouteImport.update({
  id: '/lihat/$id',
  path: '/lihat/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioIndexRoute = StudioIndexRouteImport.update({
  id: '/studio/',
  path: '/studio/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioIdRoute = StudioIdRouteImport.update({
  id: '/studio/$id',
  path: '/studio/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/daftar': typeof DaftarRoute
  '/dihantar': typeof DihantarRoute
  '/draf': typeof DrafRoute
  '/login': typeof LoginRoute
  '/peti-masuk': typeof PetiMasukRoute
  '/k/$token': typeof KTokenRoute
  '/lihat/$id': typeof LihatIdRoute
  '/studio/$id': typeof StudioIdRoute
  '/studio/': typeof StudioIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/daftar': typeof DaftarRoute
  '/dihantar': typeof DihantarRoute
  '/draf': typeof DrafRoute
  '/login': typeof LoginRoute
  '/peti-masuk': typeof PetiMasukRoute
  '/k/$token': typeof KTokenRoute
  '/lihat/$id': typeof LihatIdRoute
  '/studio/$id': typeof StudioIdRoute
  '/studio': typeof StudioIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/daftar': typeof DaftarRoute
  '/dihantar': typeof DihantarRoute
  '/draf': typeof DrafRoute
  '/login': typeof LoginRoute
  '/peti-masuk': typeof PetiMasukRoute
  '/k/$token': typeof KTokenRoute
  '/lihat/$id': typeof LihatIdRoute
  '/studio/$id': typeof StudioIdRoute
  '/studio/': typeof StudioIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/daftar'
    | '/dihantar'
    | '/draf'
    | '/login'
    | '/peti-masuk'
    | '/k/$token'
    | '/lihat/$id'
    | '/studio/$id'
    | '/studio/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/daftar'
    | '/dihantar'
    | '/draf'
    | '/login'
    | '/peti-masuk'
    | '/k/$token'
    | '/lihat/$id'
    | '/studio/$id'
    | '/studio'
  id:
    | '__root__'
    | '/'
    | '/daftar'
    | '/dihantar'
    | '/draf'
    | '/login'
    | '/peti-masuk'
    | '/k/$token'
    | '/lihat/$id'
    | '/studio/$id'
    | '/studio/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DaftarRoute: typeof DaftarRoute
  DihantarRoute: typeof DihantarRoute
  DrafRoute: typeof DrafRoute
  LoginRoute: typeof LoginRoute
  PetiMasukRoute: typeof PetiMasukRoute
  KTokenRoute: typeof KTokenRoute
  LihatIdRoute: typeof LihatIdRoute
  StudioIdRoute: typeof StudioIdRoute
  StudioIndexRoute: typeof StudioIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daftar': {
      id: '/daftar'
      path: '/daftar'
      fullPath: '/daftar'
      preLoaderRoute: typeof DaftarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dihantar': {
      id: '/dihantar'
      path: '/dihantar'
      fullPath: '/dihantar'
      preLoaderRoute: typeof DihantarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/draf': {
      id: '/draf'
      path: '/draf'
      fullPath: '/draf'
      preLoaderRoute: typeof DrafRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/peti-masuk': {
      id: '/peti-masuk'
      path: '/peti-masuk'
      fullPath: '/peti-masuk'
      preLoaderRoute: typeof PetiMasukRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/k/$token': {
      id: '/k/$token'
      path: '/k/$token'
      fullPath: '/k/$token'
      preLoaderRoute: typeof KTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lihat/$id': {
      id: '/lihat/$id'
      path: '/lihat/$id'
      fullPath: '/lihat/$id'
      preLoaderRoute: typeof LihatIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/': {
      id: '/studio/'
      path: '/studio'
      fullPath: '/studio/'
      preLoaderRoute: typeof StudioIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/$id': {
      id: '/studio/$id'
      path: '/studio/$id'
      fullPath: '/studio/$id'
      preLoaderRoute: typeof StudioIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DaftarRoute: DaftarRoute,
  DihantarRoute: DihantarRoute,
  DrafRoute: DrafRoute,
  LoginRoute: LoginRoute,
  PetiMasukRoute: PetiMasukRoute,
  KTokenRoute: KTokenRoute,
  LihatIdRoute: LihatIdRoute,
  StudioIdRoute: StudioIdRoute,
  StudioIndexRoute: StudioIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
