export const ms = {
  appName: "Kadraya",
  tagline: "Cipta & hantar kad raya digital",
  nav: {
    home: "Utama",
    drafts: "Draf",
    sent: "Dihantar",
    inbox: "Peti Masuk",
    studio: "Studio",
    logout: "Log Keluar",
  },
  auth: {
    login: "Log Masuk",
    register: "Daftar",
    username: "Nama Pengguna",
    password: "Kata Laluan",
    displayName: "Nama Paparan",
    loginSubtitle: "Selamat kembali ke Kadraya",
    registerSubtitle: "Buat akaun baharu",
    noAccount: "Tiada akaun?",
    hasAccount: "Sudah ada akaun?",
    demoHint: "Akaun demo: aminah, faizal, siti — sebarang kata laluan",
  },
  dashboard: {
    title: "Ringkasan",
    greeting: "Selamat datang",
    drafts: "Draf",
    sent: "Dihantar",
    inbox: "Peti Masuk",
    unread: "Belum dibaca",
    createNew: "Cipta Kad Baharu",
    emptyDrafts: "Tiada draf lagi. Mulakan kad raya pertama anda!",
    emptySent: "Belum ada kad dihantar.",
    emptyInbox: "Peti masuk kosong. Hantar kad antara akaun demo untuk ujian.",
  },
  studio: {
    title: "Studio Kad",
    newTitle: "Kad Baharu",
    editTitle: "Edit Kad",
    template: "Pilih Templat",
    palette: "Palet Warna",
    letter: "Mesej Surat",
    photo: "Foto",
    stickers: "Stiker",
    preview: "Pratonton",
    saveDraft: "Simpan Draf",
    send: "Hantar Kad",
    delete: "Padam Draf",
    tajuk: "Tajuk",
    sapaan: "Sapaan",
    isi: "Isi Mesej",
    namaPengirim: "Nama Pengirim",
    addPhoto: "Tambah Foto",
    removePhoto: "Buang Foto",
    addSticker: "Tambah Stiker",
    placementBackground: "Latar",
    placementFrame: "Bingkai",
    saved: "Draf disimpan",
    recipient: "Hantar kepada (pilihan)",
    skipRecipient: "Langkau — pautan sahaja",
    copyLink: "Salin Pautan",
    linkCopied: "Pautan disalin!",
    sendSuccess: "Kad berjaya dihantar",
  },
  card: {
    view: "Lihat Kad",
    open: "Buka",
    from: "Daripada",
    sentAt: "Dihantar",
    draft: "Draf",
    sent: "Dihantar",
  },
  share: {
    title: "Kad Raya Dikongsi",
    notFound: "Kad tidak dijumpai dalam pelayar ini.",
    hint: "Pautan kongsi berfungsi apabila kad wujud dalam storan pelayar yang sama.",
  },
  common: {
    back: "Kembali",
    loading: "Memuatkan...",
    error: "Ralat",
    cancel: "Batal",
    confirm: "Sahkan",
  },
} as const;
